### ISSUE TITLE
no such file: saved_models/model.yaml

### ISSUE THREAD

**Issue by iaspisw** [Chatha-Sphere/pno-ai#33]
After running run.py and generate.py, it gave me the result that  ‘no such file: saved_models/model.yaml’
I am doing research on the google magenta project (optimize the music transformer), your codes are valuable and useful for my research, so please help me to solve this problem.

**Comment by chathasphere** [comment]
I'm sorry for getting around to this so late!

I have *not* uploaded an already-trained model into this repo, so you'll have to train your own and save any hyper-parameters you use to a model.yaml file. Not the most elegant solution, but if I revisit this project I will document this part more clearly.
